NodeName=anode05 Name=gpu Type=RTX5090 File=/tmp/pilot107-rtx5090-gpu[0-3]
NodeName=anode16 Name=gpu Type=A100 File=/tmp/pilot107-a100-gpu[0-1]
NodeName=anode17 Name=gpu Type=A100 File=/tmp/pilot107-a100-gpu[0-1]
