from pathlib import Path

path = Path(__file__).resolve().parents[1] / "tests/ui/files.spec.js"
text = path.read_text(encoding="utf-8")
old = '''  const box = await firstPane.evaluate((el) => {\n    const rects = [...el.querySelectorAll(".file-tile")].map((t) => t.getBoundingClientRect());\n    const grid = el.querySelector(".filegrid").getBoundingClientRect();\n    return {\n      sx: Math.round(rects[0].left + 4),\n      sy: Math.round(grid.bottom - 5),\n      tx: Math.round(rects[1].left + rects[1].width / 2),\n      ty: Math.round(rects[0].top + 4),\n    };\n  });\n\n  await page.mouse.move(box.sx, box.sy);\n  await page.mouse.down();\n  await page.mouse.move((box.sx + box.tx) / 2, (box.sy + box.ty) / 2, { steps: 6 });\n  await page.mouse.move(box.tx, box.ty, { steps: 6 });\n  await page.mouse.up();\n\n  await expect(firstPane.locator(".filepane-selectionbar")).toContainText("2 项已选");\n'''
new = '''  const box = await firstPane.evaluate((el) => {\n    const tiles = [...el.querySelectorAll(".file-tile[data-path]")];\n    const rects = tiles.map((tile) => tile.getBoundingClientRect());\n    const grid = el.querySelector(".filegrid").getBoundingClientRect();\n    const sx = Math.round(rects[0].left + 4);\n    const sy = Math.round(grid.bottom - 5);\n    const tx = Math.round(rects[1].left + rects[1].width / 2);\n    const ty = Math.round(rects[0].top + 4);\n    const left = Math.min(sx, tx);\n    const right = Math.max(sx, tx);\n    const top = Math.min(sy, ty);\n    const bottom = Math.max(sy, ty);\n    const expectedPaths = tiles\n      .filter((_tile, index) => {\n        const item = rects[index];\n        return !(item.right < left || item.left > right || item.bottom < top || item.top > bottom);\n      })\n      .map((tile) => tile.getAttribute("data-path"));\n    return { sx, sy, tx, ty, expectedPaths };\n  });\n\n  await page.mouse.move(box.sx, box.sy);\n  await page.mouse.down();\n  await page.mouse.move((box.sx + box.tx) / 2, (box.sy + box.ty) / 2, { steps: 6 });\n  await page.mouse.move(box.tx, box.ty, { steps: 6 });\n  await page.mouse.up();\n\n  expect(box.expectedPaths.length).toBeGreaterThanOrEqual(2);\n  await expect(firstPane.locator(".filepane-selectionbar")).toContainText(`${box.expectedPaths.length} 项已选`);\n  for (const path of box.expectedPaths) {\n    await expect(firstPane.locator(`.file-tile[data-path="${path}"]`)).toHaveClass(/selected/);\n  }\n'''
if text.count(old) != 1:
    raise RuntimeError("marquee expectation shape changed")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("A5 marquee expectation made geometry-aware")
